sudo: false

language: "go"
go:
  - 1.13.x
  # - master

install:
  - go get

# branches:
#   only:
#     - master
services:
  - postgresql

before_script:
  - psql -c 'create database postgres;' -U postgres

script:
  - go test -v ./...
